server:
  port: 6789
  context-path: /spspm
#  jsp-servlet:
#    init-parameters:
#      development: true
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ems
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
  aop:
    proxy-target-class: true
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: com/baizhi/mapper/*Mapper.xml
logging:
  level:
    root: info
    com.baizhi.dao: info
    com.baizhi.service: info
  pattern:
    console: "[%p]:%m%n"
  file: Springboot.Log

